# ①占領側艦隊司令官「降伏勧告」開始
%sに通告する。\nただちにすべての軍事活動を停止し、武装を解除せよ！

# ①占領側艦隊司令官「精密爆撃」開始
%sに対して\n対地攻撃開始。\n敵の防衛施設のみに攻撃を集中せよ！

# ①占領側艦隊司令官「無差別爆撃」開始
%sに対して\n対地攻撃開始。\n地表にあるすべての建造物を破壊せよ！

# ①占領側艦隊司令官「陸戦隊降下」開始
%sに対して\n揚陸作戦開始。\nすみやかに惑星の全域を占領せよ！

# ①占領側艦隊司令官「占拠」開始
%sに対して\n揚陸作戦開始。\n敵防衛司令部を占領し、敵の反撃能力を封じるのだ。

# ①占領側艦隊司令官「扇動」開始
%s星系に告ぐ。\n君たちは自国の軍からも\n見捨てられたようだ。\nそれでも抵抗を続けるというのかね？


# ②被占領側防衛司令官「硬Ｘ線」反撃
要塞主砲、エネルギー充填……狙点固定。\n……撃て！

# ②被占領側防衛司令官「Ｔﾊﾝﾏｰ」反撃
トゥールハンマー、エネルギー充填……狙点固定。\n……撃て！

# ②被占領側防衛司令官「首飾り」反撃
アルテミスの首飾り、作動！\n各衛星は敵艦隊が射程内に入りしだい攻撃を開始せよ。

# ②被占領側防衛司令官「Ｇﾊｰｹﾝ」反撃
ガイエスハーケン、エネルギー充填……狙点固定。\n……撃て！

# ②被占領側防衛司令官「ﾐｻｲﾙ」反撃
防空システム作動！\n各防空砲台は敵艦隊が射程内に入りしだい、ミサイル攻撃を開始せよ。


# ③被占領側ｵﾍﾟﾚｰﾀｰ「硬Ｘ線」反撃
要塞主砲、エネルギー充填確認。\n……発射されます！

# ③被占領側ｵﾍﾟﾚｰﾀｰ「Ｔﾊﾝﾏｰ」反撃
トゥールハンマー、エネルギー充填確認。\n……発射されます！

# ③被占領側ｵﾍﾟﾚｰﾀｰ「首飾り」反撃
アルテミスの首飾り、作動確認。\n……攻撃が開始されました！

# ③被占領側ｵﾍﾟﾚｰﾀｰ「Ｇﾊｰｹﾝ」反撃
ガイエスハーケン、エネルギー充填確認。\n……発射されます！

# ③被占領側ｵﾍﾟﾚｰﾀｰ「ﾐｻｲﾙ」反撃
%sの防空システム作動確認。\n……ミサイル攻撃が開始されました！


# ★④占領側ｵﾍﾟﾚｰﾀｰ「硬Ｘ線」反撃被害
わが艦隊は要塞主砲の斉射を受け、%s隻の損害を被りました！

# ★④占領側ｵﾍﾟﾚｰﾀｰ「Ｔﾊﾝﾏｰ」反撃被害
わが艦隊はトゥールハンマーの斉射を受け、%s隻の損害を被りました！

# ★④占領側ｵﾍﾟﾚｰﾀｰ「首飾り」反撃被害
わが艦隊はアルテミスの首飾りの攻撃を受け、%s隻の損害を被りました！

# ★④占領側ｵﾍﾟﾚｰﾀｰ「Ｇﾊｰｹﾝ」反撃被害
わが艦隊はガイエスハーケンの斉射を受け、%s隻の損害を被りました！

# ★④占領側ｵﾍﾟﾚｰﾀｰ「ﾐｻｲﾙ」反撃被害
わが艦隊は防空ミサイルの攻撃を受け、%s隻の損害を被りました！


# ⑤占領側ｵﾍﾟﾚｰﾀｰ「降伏勧告」成功
%sより返答です。\nただちに降伏勧告に応ず、寛大な処置を乞う、とのことです。

# ⑤占領側ｵﾍﾟﾚｰﾀｰ「精密爆撃」成功
%sの防衛施設をすべて無力化しました。\n惑星はわれわれのものです！

# ⑤占領側ｵﾍﾟﾚｰﾀｰ「無差別爆撃」成功
%sの防衛施設をすべて無力化しました。\n惑星はわれわれのものです！

# ⑤占領側ｵﾍﾟﾚｰﾀｰ「陸戦隊降下」成功
陸戦隊から報告です。\n敵地上部隊を撃滅し、%sを占領した、とのことです。

# ⑤占領側ｵﾍﾟﾚｰﾀｰ「占拠」成功
突撃部隊から報告です。\n敵防衛司令部を奪取し、%sを占領した、とのことです。

# ⑤占領側ｵﾍﾟﾚｰﾀｰ「扇動」成功
工作員から報告です。\n%s政府は、和平派と抗戦派に分かれて激しく対立している、とのことです。


# ⑥被占領側ｵﾍﾟﾚｰﾀｰ「降伏勧告」成功
%sが敵の勧告に応じ、降伏を宣言しました！

# ⑥被占領側ｵﾍﾟﾚｰﾀｰ「精密爆撃」成功
%s防衛司令部との通信が途絶しました。\n敵の精密爆撃により壊滅したものと思われます。

# ⑥被占領側ｵﾍﾟﾚｰﾀｰ「無差別爆撃」成功
%s防衛司令部との通信が途絶しました。\n敵の無差別爆撃により壊滅したものと思われます。

# ⑥被占領側ｵﾍﾟﾚｰﾀｰ「陸戦隊降下」成功
%s防衛司令部との通信が途絶しました。\n敵の陸戦隊との戦闘により壊滅したものと思われます。

# ⑥被占領側ｵﾍﾟﾚｰﾀｰ「占拠」成功
%s防衛司令部との通信が途絶しました。\n敵の攻撃により壊滅したものと思われます。

# ⑥被占領側ｵﾍﾟﾚｰﾀｰ「扇動」成功
%s星系政府は、和平派と抗戦派に分かれて激しく対立している、との情報が入りました。


# ⑦被占領側防衛司令官「占拠」反論
貴様らごとき雑魚では相手にならん！\n出直してこい！


# ⑧占領側ｵﾍﾟﾚｰﾀｰ「降伏勧告」無反応
%sからは、何の返答もありませんでした。


# ⑨被占領側防衛司令官「降伏勧告」反論
降伏だと？\n笑わせるな！


# ⑩被占領側艦隊司令官「硬Ｘ線」誤射
このような混戦で要塞砲を使用するか！\n%sは何を考えているのだ？

# ⑩被占領側艦隊司令官「Ｔﾊﾝﾏｰ」誤射
このような混戦でトゥールハンマーを使用するか！\n%sは何を考えているのだ？

# ⑩被占領側艦隊司令官「首飾り」誤射
このような混戦でアルテミスの首飾りを作動させたのか！\n%sは何を考えているのだ？

# ⑩被占領側艦隊司令官「Ｇﾊｰｹﾝ」誤射
このような混戦でガイエスハーケンを使用するか！\n%sは何を考えているのだ？

# ⑪占領側ｵﾍﾟﾚｰﾀｰ「占拠」失敗
突撃部隊から報告です。\n%s艦隊の%s防衛司令部占拠作戦は中止する、とのことです。

# ⑪占領側ｵﾍﾟﾚｰﾀｰ「扇動」失敗
工作員から報告です。\n%s艦隊の%s星系政府に対する扇動工作は中止する、とのことです。

# ⑪占領側ｵﾍﾟﾚｰﾀｰ「陸戦隊降下」失敗
陸戦隊から報告です。\n%s艦隊の%sに対する降下作戦は中止する、とのことです。

# ⑫占領側ｵﾍﾟﾚｰﾀｰ「要塞砲＆ミサイル反撃」
先ほどの攻撃により、敵艦%s隻の撃破を確認しました！

# ⑬占領側ｵﾍﾟﾚｰﾀｰ「要塞砲命中」
トゥールハンマーの斉射によって、敵要塞に%sの損害を与えた模様です！

# ⑬占領側ｵﾍﾟﾚｰﾀｰ「要塞砲命中」
ガイエスハーケンの斉射によって、敵要塞に%sの損害を与えた模様です！

# ⑭被占領側ｵﾍﾟﾚｰﾀｰ「要塞砲命中」
わが要塞はトゥールハンマーの斉射を受け、%sの損害を被りました！

# ⑭被占領側ｵﾍﾟﾚｰﾀｰ「要塞砲命中」
ガイエスハーケンの斉射を受け、%sの損害を被りました！

# 要塞主砲、斉射まであと１ターン
要塞主砲、エネルギー充填まで残り６時間です。

# トゥールハンマー、斉射まであと１ターン
トゥールハンマー、エネルギー充填まで残り６時間です。

# アルテミスの首飾り、斉射まであと１ターン
アルテミスの首飾り、エネルギー充填まで残り６時間です。

# ガイエスハーケン、斉射まであと１ターン
ガイエスハーケン、エネルギー充填まで残り６時間です。
