########################################################################
#	税率変更
########################################################################

# （宰相→皇帝）
おそれながら、民への租税をかくのごとく改めようと思いますが、陛下のお考えはいかようでありましょうや。

# （皇帝→宰相）
うむ。そのようにいたせ。

# （宰相）
皇帝陛下の御名において、来期の租税は以上のように変更するものとする。

# （最高評議会）
自由惑星同盟最高評議会の決定を伝える。来期の税率は%dパーセントとする事になった。

########################################################################
#	臨時徴収
########################################################################

# （宰相→皇帝）
臣の不徳といたすところではありますが、叛徒どもの討伐費用がかさみ、通常の予算では全てをまかないきれませぬ。\nここは臨時に税を課さねばなりません。

# （皇帝→宰相）
しかたあるまい。\nしかし、このようなことはあまり繰り返さぬようにせよ。

# （宰相）
皇帝陛下の御名において、\n今期は臨時徴収を行うことを布告する。

# （最高評議会）
自由惑星同盟最高評議会の決定を伝える。\n今期には以上の通り、臨時徴税を行う事となった。\n諸君らも苦しいとは思うが、国民一丸となってこの難局を乗り切りたいと思う。

########################################################################
#	借款
########################################################################
# （宰相→皇帝）
おそれながら陛下、\nもはや、国庫にはいささかの余裕もありませぬ。\n\nフェザーンの商人どもより資金を借り受けるしかございますまい。

# （皇帝→宰相）
なに、それはまことか。\n神聖不可侵の銀河帝国もおちぶれたものよ……

# （宰相→自治領主）
自治領主、ものは相談だが、\nわが国の国債を購入し、それをもって皇帝陛下に対する忠誠の証としてみるのはどうか？

# （自治領主→宰相）
……わかりました。\nおっしゃる額だけ国債を購入する事にしましょう。\n\nわが自治領に忠誠の証をたてる機会をお与え下さった宰相閣下のご配慮、いたみいります。\nただし、わが自治領の利益分は、確実にお支払い願いますよ。

# （最高評議会→自治領主）
フェザーン自治領主どの、\nこのあたりでわが国の国債を購入されておいてはいかがかな？\n銀河帝国を打倒できれば、経済を掌握する貴国こそが最も大きな恩恵を受けるはずですからな。

# （自治領主→最高評議会）
……わかりました。\nおっしゃる額だけ国債を購入する事にしましょう。\n\n貴国には、銀河の隅々までに、民主政治の正義を知らしめるようにしてもらわねばなりませんからな。\nただし、わが自治領の利益分は、確実にお支払い願いますよ。


########################################################################
#	要職任命
########################################################################

# （帝国宰相→皇帝）
三長官の職を以上のごとく任命したく思いますが、いかがでしょうか。

# （皇帝→帝国宰相）
よいよい。\nそなたの好きなようにいたせ。

# （帝国宰相）
皇帝陛下の御名において、\n三長官職を任命する。\n謹んで拝命せよ。

# （国家元首）
軍人事に関する自由惑星同盟最高評議会の決定を伝える。\n同盟憲章に準じ、以上の将官を指揮官に任命する。


########################################################################
#	諜報官任命
########################################################################

# 解任（統帥本部→相手）
%s、\n卿の統帥本部調査局長の任を解く。

# 任命（統帥本部→相手）
%s、\n卿を統帥本部調査局長に任ずる。

# 返事（相手→統帥本部）
つつしんで拝命いたします。

# 兼任（統帥本部）
以後、調査局長は私が兼任する。

# 解任（統合作戦→相手）
%s、\n貴官の統合作戦本部情報部長の任を解く。

# 任命（統帥本部→相手）
%s、\n貴官を統合作戦本部情報部長に任ずる。

# 返事（相手→統合作戦）
わかりました。

# 兼任（統合作戦本部）
以後、情報部長は\n統合作戦本部長、\nもしくは次長が兼任する。


########################################################################
#	防衛司令官任命（帝国・同盟共用）
########################################################################

# 共通宣言
星系駐留防衛司令官の異動を伝える。

# 内定者列挙
%s

# 解任
以上の者は、防衛司令官の任を解く。

# 自分を解任
%s\n小官の担当。

# 任命
以上の者は、新たに防衛司令官に任ずる。\nただちに任地へ赴くように。

# 返事
つつしんで拝命いたします。

########################################################################
#	士官配属
########################################################################

# 共通宣言
士官の異動を伝える。\n以下の者は、%d年%d月%d日を以て、\n%s星系管区に配属するものとする。

# 内定者列挙
#%s

# 共用２
また、同日を以て、\n以下の者を%s星系管区に配属するものとする。

# 内定者列挙
%s

# 軍務尚書赴任
#%s星系管区には、私自身が赴く。

# プレイヤー任命（帝国）
卿には%s星系管区に行ってもらう。\nただちに任地へ赴くように。

# プレイヤー任命（同盟）
貴官には%s星系管区に行ってもらう。\nただちに任地へ赴くように。

# 返事
#つつしんで拝命いたします。


########################################################################
#	造兵廠建設
########################################################################

# 共通宣言１（帝国・同盟共用）
今期の造兵廠整備計画を伝える。

# 建設惑星列挙
%s

# 建設・撤去決定（帝国・同盟共用）
造兵廠の整備は、次に述べる各星系で実行される。

# 建設中止（帝国・同盟共用）
%s残念ではあるが、\n次に述べる各星系の造兵廠整備は中止することとなった。

# 共通宣言２（帝国・同盟共用）
以上である。


########################################################################
#	防衛基地建設
########################################################################

# 共通宣言１（帝国・同盟共用）
今期の防衛基地整備計画を伝える。

# 建設惑星列挙
%s

# 建設・撤去決定（帝国・同盟共用）
防衛基地の整備は、次に述べる各星系で実行される。

# 建設中止（帝国・同盟共用）
%s残念ではあるが、\n次に述べる各星系の防衛基地整備は中止することとなった。

# 共通宣言２（帝国・同盟共用）
以上である。


########################################################################
#	駐留基地建設
########################################################################

# 共通宣言１（帝国・同盟共用）
今期の駐留基地整備計画を伝える。

# 建設惑星列挙
%s

# 建設・撤去決定（帝国・同盟共用）
駐留基地の整備は、次に述べる各星系で実行される。

# 建設中止（帝国・同盟共用）
%s残念ではあるが、\n次に述べる各星系の駐留基地整備は中止することとなった。

# 共通宣言２（帝国・同盟共用）
以上である。

# 基地削減時の駐留予定艦隊撤退
ついては、基地の削減にともない、艦隊駐留の見直しを願いたい。

# 返答（宇宙艦隊司令長官→統帥本部総長）
承知した。

# 返答（宇宙艦隊司令長官→統合作戦本部長）
了解しました。

########################################################################
#	艦隊配属
########################################################################

# 共用１（宇宙艦隊→艦隊司令）
%d年%d月%d日を以て、\n%s星系管区に新たに艦隊を配属するものとする。\L配属されるのは以下の各艦隊である。

#　出撃艦隊列挙（宇宙艦隊→艦隊司令）
#%s%s

# 共用２（宇宙艦隊→艦隊司令）
また、同日を以て、\n%s星系管区に新たに艦隊を配属するものとする。\L配属されるのは以下の各艦隊である。

# 出撃艦隊列挙（宇宙艦隊→艦隊司令：司令長官が配属）
我が%s

# 出撃艦隊列挙（宇宙艦隊→艦隊司令：その他が配属）
%sの%s

# （宇宙艦隊→プレイヤー）
#宇宙艦隊司令長官直属の艦隊も、これに含まれる。

# （宇宙艦隊→プレイヤー）
#卿の第%d艦隊も、これに含まれる。\n別命あるまで、かの地において待機せよ。

# （宇宙艦隊→プレイヤー）
#貴官の第%d艦隊も、これに含まれる。\n別命あるまで、かの地において待機せよ。

# （プレイヤー→宇宙艦隊）
#了解しました。

# 帝国（司令長官の締め）
以上である。\n願わくば、皇帝陛下の御威光をあまねく銀河に知らしめんことを。

# 同盟（司令長官の締め）
以上である。\n貴官の健闘を期待する。

# ?????
#はぁ、わかりました。

# 出撃ナレーション１
#宇宙暦%d年、帝国暦%d年%d月%d日、\n%sに率いられた%d個艦隊%ld隻が、\n%s星域に向けて、%s

# 出撃ナレーション２
#同じく%sに率いられた%d個艦隊%ld隻が、\n%s星域に向けて、%s

########################################################################
#	軍事作戦
########################################################################

# 汎用（作戦列挙）
%s

# 決行１（統帥本部・統合作戦本部→宇宙艦隊司令長官）
%s以下のような\n作戦を決定した。\nすなわち、

# 決行２（統帥本部・統合作戦本部→宇宙艦隊司令長官）
以上を実行する。

# 撤退１（統帥本部・統合作戦本部→宇宙艦隊司令長官）
%s以下のような\n作戦より艦隊を撤退させることを決定した。\nすなわち、

# 撤退２（統帥本部・統合作戦本部→宇宙艦隊司令長官）
以上はただちに作戦を中止して撤退するものとする。

# 作戦中止１（統帥本部・統合作戦本部→宇宙艦隊司令長官）
%s以下のような\n作戦の発令を撤回する\nことを決定した。\nすなわち、

# 作戦中止２（統帥本部・統合作戦本部→宇宙艦隊司令長官）
以上は中止するものとする。

# 作戦変更１（統帥本部・統合作戦本部→宇宙艦隊司令長官）
%s以下の作戦について一部修正を加える。\nすなわち、

# 作戦変更２（統帥本部・統合作戦本部→宇宙艦隊司令長官）
以上である。

# 返答（宇宙艦隊司令長官→統帥本部総長）
承知した。

# 返答（宇宙艦隊司令長官→統合作戦本部長）
了解しました。


########################################################################
#	艦隊出撃
########################################################################

# 共用１（宇宙艦隊→艦隊司令）
%d年%d月%d日を以て、\n%s星系に対する%sを開始する。\nなお、この作戦には\n以下の艦隊が動員される。

# 共用２（宇宙艦隊→艦隊司令）
また、同日を以て、\n%s星系に対する%sを開始する。\nなお、この作戦には\n以下の艦隊が動員される。

# 出撃艦隊列挙（宇宙艦隊→艦隊司令：宇宙艦隊司令長官出撃）
我が%s

# 出撃艦隊列挙（宇宙艦隊→艦隊司令：その他艦隊出撃）
%sの%s

# 作戦総司令官の任命（帝国宇宙艦隊司令長官）
作戦の総指揮は本職が執る。

# 作戦総司令官の任命（同盟宇宙艦隊司令長官）
作戦の総指揮は小官が執る。

# 作戦総司令官の任命（帝国プレイヤ）
作戦の総指揮は卿が執ってくれ。\n双頭の鷲の赴くところに必ず勝利ありと確信しているぞ。

# 作戦総司令官の任命（同盟プレイヤ）
作戦の総指揮は貴官に任せることになった。\n勝利を確信しているぞ。

# 作戦総司令官の任命（その他）
作戦の総指揮は%sが執る。

# 帝国総司令官の返答
はたしてうまくいきますかな…

# 同盟総司令官の返答
やつらに目にものをいわせてくれましょう。

# ヤン総司令官の返答
はぁ、なるべく努力します。

# アイゼナッハ総司令官の返答
…

# 帝国（司令長官の締め）
以上である。\n大神オーディンよ、心あらば、わが正義の軍をして凱歌をあげさせたまえ。

# 同盟（司令長官の締め）
#以上である。\n専制主義の闇の彼方から自由の暁をわれらの手で呼び込もうではないか。

# 出撃ナレーション１
宇宙暦%d年、帝国暦%d年%d月%d日、\n%sに率いられた%d個艦隊%ld隻が、\n%s星域に向けて、%s

# 出撃ナレーション２
同じく%sに率いられた%d個艦隊%ld隻が、\n%s星域に向けて、%s

########################################################################
#	輸送
########################################################################

# （宇宙艦隊司令長官）
%d年%d月%d日を以て、\n%s星系・惑星%sに対する輸送作戦を行なう。\Lなおこの作戦には以下の艦隊が動員される。

# （宇宙艦隊司令長官）
また、同日を以て、\n%s星系・惑星%sに対する輸送作戦を行なう。\Lなおこの作戦には以下の艦隊が動員される。

# 艦隊列挙（その他）
%sの%s

# （宇宙艦隊→プレイヤー）
#以上が動員される。

# （宇宙艦隊→プレイヤー）
#なお、この作戦は宇宙艦隊司令長官直属の艦隊によって遂行される。

# （宇宙艦隊→プレイヤー）
#この作戦は、卿の艦隊に一任する。

# （宇宙艦隊→プレイヤー）
#この作戦は、貴官の艦隊に一任する。

# （プレイヤー→宇宙艦隊）
#了解しました。

# 出撃ナレーション１
# 宇宙暦%d年、帝国暦%d年%d月%d日、\n%sに率いられた第%d艦隊%ld隻が、\n%s星域に向けて、%s

# 出撃ナレーション２
# 同じく%sに率いられた第%d艦隊%ld隻が、\n%s星域に向けて、%s

########################################################################
#	艦隊編成・再編成・解散
########################################################################

#汎用１
%sの%s。

# 新設
%s%s以下の艦隊を新設する。

# 再編成
%s%s以下の艦隊を再編成する。

# 解散
%s%s以下の艦隊を\n残念ながら解散とする。

# 汎用２
以上である。


########################################################################
#	機密入手
########################################################################

#（統帥本部総長→調査局長）
%s、\n卿に諜報作戦の開始を命ずる。

#（調査局長→統帥本部総長）
御意。

#（統合作戦本部長→情報部長）
%s、\n貴官に諜報作戦の開始を命ずる

#（情報部長→統合作戦本部長）
わかりました。

#（統帥本部総長・統合作戦本部（次）長）
これより、諜報作戦を開始する。


########################################################################
#	治安回復
########################################################################

#（軍務尚書→防衛司令官）
%s、\n卿に%s星系の治安の回復を命ずる。いかなる手段を使ってもよいぞ。

#（防衛司令官→軍務尚書）
御意。

#（統合作戦本部長→防衛司令官）
%s、\n貴官に%s星系の治安の回復を命ずる。いかなる手段を使ってもかまわん。

#（防衛司令官→統合作戦本部長）
わかりました。


########################################################################
#	予算配分
########################################################################

#（宰相→皇帝）
この度、国庫に入りました資金を、以上のように配分しようと思いますが、陛下のお考えはいかがでありましょうや。

#（皇帝→宰相）
よいよい、そちの好きなようにいたせ。

#（宰相）
皇帝陛下の御名において、この資金は以上のように配分するものとする。

#（同盟議長）
この度、国庫に入った資金は、以上のように配分することとなった。

#（弁務官）
確かに償還分の資金はいただきました。これからも、このような友好的な関係を維持したいものですな。


########################################################################
#	提案工作
########################################################################

#（キャラ→宰相）
おそれながら申し上げますが、非常の時には非常の策を以て応じねば、国を損なうこととなりましょう。

#（宰相→キャラ）
卿の言うのはもっともな事である。\nただちに、陛下に奏上しよう。

#（宰相→皇帝）
%sはかように申しておりますが、いかがいたしましょうか。

#（皇帝→宰相）
よいではないか。\nあの者の好きなようにやらせてみるがよい。

#（宰相→キャラ）皇帝が存命
%sに国政に関する非常大権を与える。\n諸卿らも、かの者の言葉は陛下の御言葉であると心得よ。

#（キャラ→宰相）
陛下の有難き御言葉、身に余る光栄にございます。

#（宰相→キャラ）皇帝がいない
わかった。\n卿の好きなようにしてみるがよい。

#（キャラ→同盟議長）
全て私にお任せください。\nこれらの件が成功に終われば、次の選挙での支持率に大きな影響を与えることでしょう。

#（同盟議長→キャラ）
なるほど、それもそうだな。\n貴官に一任することにしよう。

#（キャラが宰相・議長）
非常の時には非常の策…か。\nやむをえんな。

########################################################################
#	辞任（帝国）
########################################################################

#（キャラ→宰相）
宰相閣下に申し上げます。\nこの度、小官は思うところあって軍を去ることとしました。\n\n後事は、よしなに処理願います。

#（宰相→キャラ）
%s、何も辞めるまでの事はないのではないか。

#（キャラ→宰相）
小官は長く軍務につきすぎました。\n後身に道を譲るのが、小官の最後の御奉公と心得ます。

#（宰相→キャラ）
そうか、わかった。\n長年の忠勤、苦労であったな。

#（宰相布告）
諸将に申し渡しておく。\n%d年%d月を以て、%sは軍務より退くことになった。\n以後、心得置くように。

########################################################################
#	辞任（同盟）
########################################################################

#（キャラ→議長）
議長閣下に申し上げます。\nこの度、小官は思うところあって軍を去ることとしました。\n\n後事は、よしなに処理願います。

#（議長→キャラ）
%s、何も辞めるまでの事はないのではないか。

#（キャラ→議長）
小官は民主主義国家の軍人として、引き際を誤りたくないと思いますので。

#（議長→キャラ）
そうか、辞める意思は堅いようだな。\n議会にはその旨を報告しておこう。

#（議長布告）
この場を借りて報告しておくことがある。\L%d年%d月を以て、%sは軍務より退くことになった。\L盛大な拍手を以て、%sの軍歴に敬意を示そうではないか。

########################################################################
#	償還不能
########################################################################

#（フェザーン→帝国・同盟）１
わが自治領に対する返済が\n滞っているようですな。

#（フェザーン→帝国・同盟）２
ふ。愚かなものだ。\nもはや、これからの宇宙は\n武力ではない。\n経済こそが支配するのだ。

#（フェザーン→帝国）１
これでは銀河帝国に投じている我々の資本を引き上げざるをえませんな。

#（フェザーン→帝国）２
それで帝国の経済が破綻したとしても、我々の関知するところではありますまい。

#（フェザーン→同盟）１
これでは貴国に投じている\n我々の資本を引き上げざるをえませんな。

#（フェザーン→同盟）２
それで貴国の経済が破綻したとしても、我々の関知するところではありますまい。

#（宰相・議長→フェザーン）１
・・・

#（宰相→フェザーン）２
うぬ…

#（議長→フェザーン）２
し、しかし…

########################################################################
#	     各種エラーメッセージ
########################################################################

# 艦隊結成　旗艦部隊未設定
\n旗艦部隊の指示を願います。

# 基地建設の予算超過（造兵廠・防衛・駐留基地）
\n予算超過です。\n訂正願います。

# 最大許容艦隊数超過（艦隊出撃）
\n本作戦の\n許容出撃数を超過しています。

# 諜報不可能（諜報官任命・機密入手）
おそれながら我が軍による\nフェザーン強行制圧のため、\n現在、敵側情報の入手経路は\n完全に失われております。

# 借款不可能
ご指示の手続きですが、\nフェザーン自治領が\n既に転覆しているため、\n処理できません。

# 敵地飛び越し警告
閣下。確認までに申し上げますが、\nこの星系は航路不確定のため、\n艦隊運用に重大な支障を招く事\nが予想されます…

# 敵地飛び越し警告（艦隊幕僚から）
お待ち下さい、閣下。\n敵地のただ中に飛び込んでは、兵の士気をいたずらに下げるばかり。\nもはや闘いどころではありません。\nどうかご再考を。

# フェザーン占領警告
閣下。今のご指示の内容ですが…、フェザーン自治領が転覆しますと、わが国の情報・財政は相当な打撃を受けますが…

# フェザーン占領警告（艦隊幕僚から）
…フェザーン自治領が転覆すれば、わが国の情報・財政面における\n打撃は必至。\n何卒思いとどまられた方がよろしいかと…

# 艦隊運営費不足
予算不足のため、\n艦隊運営費の支出は\n当面停止します。

# 要職者が首都星系に不在
%s閣下は\n現在、首都星系不在のため、\n手続きがとれません。

# 輸送艦隊枠なし
\n艦隊の空き枠がないため、\n輸送の手続きはできません。

########################################################################
#	その他メッセージ
########################################################################

# 軍事計画漏洩
%sより報告。\n通信情報の分析により、%s軍の動向が判別。\n敵は、%s星域%sを\n目標として作戦行動を行なっている模様。

# 敵艦隊遭遇
緊急報告。\n%s星域において、\n敵艦隊と遭遇した模様。

# 敵艦隊遭遇（敵内乱）
報告いたします。\n%s星域において、\n敵艦隊同士による戦闘が\n開始されたものと思われます。

# 戦闘継続
報告いたします。\n%s星域における戦闘は、\n依然続いている模様です。

# 敵星系への侵攻開始
報告いたします。\n我が軍による\n%s星域侵攻作戦が\n開始された模様です。

# 敵星系への侵攻開始
報告いたします。\n我が軍による\n%s星域侵攻作戦は\n今なお継続中です。

# 敵軍の侵入
緊急報告。\n%s星域に、\n敵艦隊が侵入した模様。

# 敵軍の侵入継続
報告いたします。\n%s星域より、\n引き続き援軍の要請が\n届いております。

# 自軍の惑星奪還
報告いたします。\n%s星域において、\n惑星奪還が\n開始された模様です。

# 自軍の惑星奪還継続
報告いたします。\n%s星域の惑星奪還は\n今なお継続中です。

# 敵軍の惑星奪還
報告いたします。\n%s星域において、\n敵軍は惑星奪還を\n開始した模様です。

# 敵軍の惑星奪還継続
報告いたします。\n敵軍による\n%s星域の惑星奪還は、\n依然続いている模様です。

# 勝利報告
報告いたします。\n%s星域の戦闘は、\nわが軍の大勝利に終わりました。

# 暴動発生その１
緊急報告。\n%s星域において、\n市民による大規模な暴動が発生。\n軍事施設の一部も破壊された模様。

# 暴動発生その２
緊急報告。\n%s星域において、\n市民による大規模な暴動が発生。\n行政機関・放送局等、都市中枢部はほぼ占拠された模様。

# 基地建設完了
報告いたします。\n%s星系管区\n惑星%sの\n%s整備が完了いたしました。

# 新任士官着任報告
%s、\nただいま着任しました。\nこれより任務につきます。

# 作戦星系到着
%s、\n%s星域に到着。\nこれより作戦を遂行。

# 艦隊の首都星帰還
%s、\nただいま%sに帰還。

# 新配属地へ到着
%s、\nただいま配属管区\n%s星域に到着。

# 防衛司令官の任地到着
%s、\n着任地%sに\n到着しました。

# 防衛司令官の帰還
%s、\n任務を終え、\n%sに帰還。

# 崩御（宰相の台詞）
…なに、それはまことか…。

#帝国昇進（皇帝・宰相）
%s、\nこの度の武勲、まことに見事であった。

#帝国昇進（キャラ）
これも、ひとえに陛下のご威光の賜物でございます。

#帝国昇進（皇帝・宰相）
叛乱軍討伐の功績により、汝、\n%sを\n帝国軍%sに任ず。

#同盟昇進（議長）
%s、\n君を%sに昇進させることが決まった。

#同盟昇進（キャラ）
ありがとうございます。

#同盟昇進（議長）
これからも、自由と民主主義の存続のために努力してもらいたい。

#クーデタ決行（帝国・同盟）
ここで決めた以上は、\nもはや後に退けんな…

#クーデタ蜂起星系の決定ガイド（帝国・同盟）
さて、\n問題はどこで事を起こすかだ…

#一部艦隊の消息途絶（オペレータ報告）
緊急事態発生。\nわが軍艦隊、及び士官の一部が\n突如消息を絶った模様。\nまた、%sのコンピュータに\n原因不明の障害が発生。\n現在、一切の人事処理が不可能。

#一部艦隊の消息途絶（宰相・議長感想）
\n…。\nやつらめ、何を企んでいるのだ。

#クーデタ発生報告
緊急報…？\nい…、異変です！\nクーデタが発生しました。

#クーデタ発生報告（敵国）
緊急報告。\n敵国でクーデタの発生した模様。

#要塞移動までの残りターン報告
ガイエスブルク要塞の\n移動決行まであと%d日です。

#要塞移動中止宣言１
ガイエスブルグ要塞陥落のため、\n残念ながらイゼルローン星域への移動は中止します。

#要塞移動中止宣言２
イゼルローン陥落のため、\nガイエスブルグ要塞の移動は中止します。

#移動要塞出現（同盟）
イゼルローンより緊急入電！\n回廊内に敵要塞が出現。\n至急援軍を乞う、とのことです。

#死亡確認報告
\n報告します。%sの死亡が確認されました。

#移動中負傷確認報告
報告します。%sが\n航行中に負傷された模様です。

#地球教徒負傷報告
%s%sより報告。\n部下の中に紛れ込んでいた地球教徒の襲撃を受け、負傷せり。\n指揮には当面支障なし。

#艦隊全滅報告
%s、全滅の模様。

#能力上昇１
私も、ようやく\n%sの何たるかが\nわかったような気がするな。

#能力上昇２  148/100
俺も、ようやく\n%sの何たるかが\nわかったような気がするぜ。

#能力上昇３  79/144
私も、ようやく\n%sの何たるかが\nわかったような気がしますわ。

#能力上昇４  157
ぼくも、ようやく\n%sの何たるかが\nわかったような気がします。

#能力上昇５  156
私も、ようやく\n%sの何たるかが\nわかったような気がするなぁ。

#能力上昇６  10
%sの何たるかを知り得たのは幸いだった……。

#能力上昇７  15/83
私も%sとは何かが\nわかったような気がします。

#能力上昇８  81
%sとは、こういうものだということだな。

#帝国の最高権力者を戦死せしめた報告
宇宙暦%d年%d月%d日、\n万民に圧政を強いてきた\n帝国宰相%sは\n%s星系において戦死した。\n専制の闇は終わり、民主主義の夜明けが始まるのだ。\n共和国万歳！

#同盟の最高権力者を戦死せしめた報告
帝国暦%d年%d月%d日、\n自由惑星同盟を僭称する\n叛徒の指導者%sは\n%s星系において戦死した。\n宇宙はこれからも永遠に皇帝陛下によって統治されるのだ。\n皇帝陛下万歳！

#帝国の首都を占領した報告
宇宙暦%d年%d月%d日、\n銀河帝国の帝都ヴァルハラ星系は\n自由惑星同盟の遠征軍によって攻略された。\n専制の闇は終わり、\n民主主義の夜明けが始まるのだ。\n共和国万歳！

#帝国の首都を占領した報告
帝国暦%d年%d月%d日、\n自由惑星同盟を僭称する叛徒の牙城、\nバーラト星系は\n銀河帝国の遠征軍によって攻略された。\n宇宙はこれからも永遠に皇帝陛下によって\n統治されるのだ。\n皇帝陛下万歳！

#帝国が返済不能で敗北
宇宙暦%d年%d月%d日、\n銀河帝国は自由惑星同盟軍の進軍を待つまでもなく、自らの失政が引き起こした混乱によって自滅した。\n専制の闇はついに終わりを告げたのだ。\nいつの日にか、帝国領にも民主主義の息吹が芽生えることになるであろう。

#同盟が返済不能で敗北
帝国暦%d年%d月%d日、\n自由惑星同盟は銀河帝国軍の進軍を待つまでもなく、自らの失政が引き起こした混乱によって自滅した。\n皇帝陛下の御心にそぐわぬ叛徒どもは、ついにこの銀河より一掃されたのだ。\nいつの日にか、この宇宙すべてに皇帝陛下の御威光が行き渡ることになるであろう。

########################################################################
#	    絵つきメッセージ
########################################################################

# 艦隊出撃（帝国）
  宇宙暦%d年、帝国暦%d年%d月%d日、%sに率いられた%d個艦隊%ld隻は、銀河帝国の首都・オーディンを出撃した。

# 艦隊出撃（同盟）
  宇宙暦%d年、帝国暦%d年%d月%d日、%sに率いられた%d個艦隊%ld隻は、自由惑星同盟の首都・ハイネセンを出撃した。

# 艦隊出撃（その他）
  宇宙暦%d年、帝国暦%d年%d月%d日、%sに率いられた%d個艦隊%ld隻は、本拠地%sを出撃した。

# 崩御
  帝国暦%d年%d月%d日、ゴールデンバウム王朝第３６代皇帝フリードリヒⅣ世は崩御した。死因は、急性の心臓疾患であった。

#帝国昇進
  帝国暦%d年%d月%d日、%sは帝国軍%sに任じられた。

#同盟昇進
  宇宙暦%d年%d月%d日、%sは同盟軍%sに任じられた。

#クーデタ（帝国貴族）
  帝国暦%d年%d月%d日、%s星系において、%sを盟主とする貴族たちの軍事組織が誕生した。\n  この組織は、盟約の交わされた場所の名をとり、リップシュタット反帝連合軍と呼ばれることになる。

#クーデタ（帝国一般）
  帝国暦%d年%d月%d日、%sらは%s星系において、銀河帝国に対して反旗を翻した。\n  国政を專断する帝国宰相%sを、実力で排除せんというのが彼の主張であった。

#クーデタ（同盟）
  宇宙暦%d年%d月%d日、%sを首謀者とする自由惑星同盟救国軍事会議は、%s星系において反旗を翻した。\n  彼らは同盟憲章の停止を宣言し、救国軍事会議の決定と指示がすべての法に優先する、と布告した。

#クーデタ（帝国２）
  帝国宰相%sは宰相府において逮捕され、その場で自裁を強制されて息絶えた。そして、次の帝国宰相には、%sが銀河帝国皇帝の御名をもって任じられる。\n　後世の史書は、この日より帝国の最高権力はすべて%sの手中に帰した、と記している。

#クーデタ（同盟２）
  %sは武装兵を引き連れて最高評議会議場に乗り込み、その圧力によって自らを終身の最高会議議長に選出させた。同盟の最高権力は、ついに%sの手中に帰したのである。\n　後世の歴史は、この日をもって自由惑星同盟の民主主義がその終焉を迎えた、と書き記している。

#クーデタ（帝国３　正規軍側勝利）
  討伐軍の勝利によって、叛乱は潰え去った。首謀者%sをはじめ、他の叛乱者たちもすべて、戦死するか逮捕さるに至った。事態の完全な収拾にはまだ若干の時間が必要であったが、銀河帝国は再びその軍事力を国外へ向けることが可能となったのである。

#クーデタ（同盟３　正規軍側勝利）
  鎮圧部隊の勝利によって、クーデタは潰え去った。首謀者%sをはじめ、他の叛乱者たちもすべて、戦死するか逮捕されるかに至った。事態の完全な収拾にはまだ若干の時間が必要であったが、自由惑星同盟は再びその軍事力を国外へ向けることが可能となったのである。

#クーデタ（帝国４　実行計画者の元帥特進）
  同時に、新帝国宰相の%sは、叛乱を主導した%sに対し、元帥号を以てその功績に報いた。

#クーデタ（帝国４　実行計画者が元帥の場合の恩賞）
  同時に、新帝国宰相の%sは、叛乱を主導した%sに対し、極めて多大なる発言権を与える事でその功績に報いた。

#クーデタ（同盟４　実行計画者の元帥特進）
  同時に、新しい同盟指導者%sは、叛乱を主導した%sに対し、元帥号を以てその功績に報いた。

#クーデタ（同盟４　実行計画者が元帥の場合の恩賞）
  同時に、新しい同盟指導者%sは、叛乱を主導した%sに対し、極めて多大なる発言権を与える事でその功績に報いた。

#要塞移動（帝国側メッセージ）
　帝国暦%d年%d月%d日、要塞移動作戦が開始された。ガイエスブルク要塞は長距離ワープに成功し、イゼルローン要塞に対して、史上初の要塞同士による対決を強いることになったのである。

#要塞移動（同盟側メッセージ）
　宇宙暦%d年%d月%d日、イゼルローン回廊に帝国軍の移動要塞が出現した。\n  帝国軍は既存の要塞にワープエンジンを取り付け、１万光年を隔てたイゼルローン要塞の前面に、それをワープアウトさせたのである。

########################################################################
#	ラインハルト改姓
########################################################################

# 皇帝１
……そなたに、ローエングラム伯爵家を継がせることにした。武門の名流であって、そちにふさわしいのでな。

# ラインハルト１
身に余る光栄でございます。

# 皇帝２
伯爵家など、誰が継ぎ、誰が絶やしても大したことではないのだがな。大したことだと思いこんでいる輩の多いことよ。

# ラインハルト２
……

# 皇帝３
どうかな、余はこうも思うのだ。そなたをいっそ侯爵にしてやろうかと。

# ラインハルト３
侯爵……でございますか。\nありがたき仰せながら、臣にとっては伯爵号でさえ身に余る地位でございます。侯爵など、いわば雲の上の身分、臣の手の届くところではございません。

# 皇帝４
そうか、雲の上の身分に思えるか。皇帝は侯爵よりもえらいのだ、ということに世の中ではなっているが、そなたもそう思うか。

# ラインハルト４
……はい

# 皇帝５
そうか、そう思うか。

# ナレーション
  帝国暦%d年%d月%d日、ラインハルト・フォン・ミューゼルはローエングラム伯爵家を継ぎ、以後、ラインハルト・フォン・ローエングラムと名乗ることになる。


########################################################################
# 機密漏洩（帝国）
########################################################################

# ルビンスキー
宰相閣下も興味ある話かと思いますが、わが自治領が得た同盟の情報をお教えしましょう。

# 宰相
しかし自治領主、なぜそのような情報を教えてくれるのだ？

# ルビンスキー
宰相閣下のおっしゃりようは、いささか心外ですな。\n\n\nわが自治領が帝国の不利益になるようなことを一度でもしたことがありますか？

# 宰相
いや、記憶にはない。\nもちろん、わが帝国はフェザーンの忠誠に完全な信頼をよせているからな。

# ルビンスキー
ふふ、なるほど。

########################################################################
# 機密漏洩（同盟）
########################################################################

# ルビンスキー
議長閣下も興味ある話かと思いますが、わが自治領が得た帝国の情報をお教えしましょう。

# 議長
しかし自治領主どの、なぜそのような情報を教えてくれるのですかな？

# ルビンスキー
議長閣下のおっしゃりようは、いささか心外ですな。\n\n\nわが自治領が自由惑星同盟の不利益になるようなことを一度でもしたことがありますか？

# 議長
記憶にはないですな。\nいや、もちろん、わが同盟はフェザーンの友誼に完全な信頼をよせていますが……。

# ルビンスキー
ふふ、なるほど。

########################################################################
# 要塞移動
########################################################################
#思案１
  かつて、帝国軍が敵の勢力範囲の奥深く侵攻しえたのは、イゼルローン要塞を橋頭堡として利用できたからである。\n  だが現在、かの要塞は敵の手中にあり、これがため、帝国軍は回廊を通過する事ができない。

#思案２
  イゼルローンさえ陥落させれば、帝国軍は一気に同盟領を制圧する事も可能であろう。

#思案３
  しかし、かの要塞は難攻不落であり、戦艦の主砲をもってしても、その装甲は傷つけることができない。\n  艦隊によって攻略し得ないとすれば、どうすべきであろうか。

#思案４
  唯一の方法は、イゼルローンに匹敵する火力と装甲をもって対抗することである…

#実行か否か
手ごろな要塞、すなわちガイエスブルク要塞を移動させ、イゼルローンを攻略するべきだろうか？

#撤回
しかし、この作戦のコストに見合う戦果は、おそらく得られないだろう…

#オペレータ
#宰相閣下に、科学技術総監が面会の許可を求めてきております。

#宰相
……つまり、イゼルローン要塞の前面に、それに対抗するための拠点となる我が軍の要塞を構築するというのか。

#シャフト
さようです、閣下。

#宰相
構想としては悪くないが、成功するにはひとつ条件が必要だな。

#シャフト
それは？

#宰相
我が軍が要塞を構築する間、同盟軍の奴らが黙ってそれを見物し、けっして妨害しない、という条件付きだ。

#シャフト
……

#宰相
そいつは魅力的なアイデアではあるが、実際的とは言いがたいな。\n\n改良すべき点を改良した上で、いずれ改めて提案してもらうとしよう。

#シャフト
お待ち下さい。その条件は不要です。なぜなら、私の思案は……\n\nすでに構築された要塞、ガイエスブルク要塞をイゼルローン回廊まで移動させるというものだからです。

#宰相
……

#宰相
あの巨大な要塞を動かすというのか！\nそんなことは夢物語にすぎん。\n\n科学技術総監の地位は、たわごとを並べ立てる輩には、任せておけんな。

#シャフト
ううむ……。

#宰相
ガイエスブルク要塞に跳躍航行エンジンを取り付け、１万光年を航行し、イゼルローンに要塞同士の決戦を強いる！\n%d年%d月%d日を以て、作戦開始とする！

########################################################################
# キルヒアイス戦死
########################################################################

#ラインハルト
\n嘘だ……キルヒアイスが私を置いて先に死ぬわけがないんだ！

#ラインハルト
姉上……キルヒアイスが……。

#アンネローゼ
わかっています。\nあなたが、そんなに言いづらそうにすることは１つしかありません。\n……キルヒアイスが死んだのですね。

#ラインハルト
……。

#アンネローゼ
かわいそうなラインハルト……。\nあなたはもう失うべきものを持たなくなってしまったわね。

#ラインハルト
……いえ、まだ私には姉上がいます。\nそうですね、姉上、そうでしょう？

#アンネローゼ
そう、私たちはおたがいの他に、\nもう何も持たなくなってしまった……

#ラインハルト
姉上……。

#アンネローゼ
当分はおたがいに会わないようにしましょう。

#ラインハルト
姉上！

#アンネローゼ
私はあなたの傍にいないほうがいいのです。\n生き方が違うのだから……私には過去があるだけ。\nでも、あなたには未来があるわ。

#ラインハルト
……。

#アンネローゼ
疲れたら、私のところにいらっしゃい。\nでも、まだあなたは疲れてはいけません。

#ラインハルト
わかりました。\n姉上がそうおっしゃるなら、お望みのとおりにします。\nそして、宇宙を手に入れてからお迎えに上がります。

#ラインハルト
でも、お別れの前に教えてください。\n姉上はキルヒアイスを……愛していらしたのですか？

#アンネローゼ
……。

#ナレーション
  半身を失ったラインハルトは、それを補うために何かを新たに身につけようとしている。\n  それは何者にとって歓迎すべきであり、何者にとって忌避すべきものであるのだろうか。

########################################################################
# クーデタ
########################################################################

#叛乱討伐司令官の決定
これより、叛乱討伐総司令官を指名する。

#帝国宰相より
%s、勅命である。\n%d年%d月%d日をもって、卿を叛乱軍討伐の総司令官に任ずる。私党を組んで皇帝陛下に反逆をたくらむ%s以下の国賊を討伐せよ。

#討伐司令官より
御意。必ずや奴らを捕らえ、閣下の御前に引き据えて御覧にいれます。

#同盟議長より
%sも知っていると思うが、%s以下の急進派が叛乱を起こした。\Lそこで、最も信頼すべき軍人である貴官を、叛乱軍討伐の総司令官に任ずる。\L君の用兵の才を生かし、すみやかに秩序を回復してくれたまえ。

#討伐司令官より
わかりました。同盟憲章に従い、軍人としての義務を果たします。

#帝国宰相が討伐司令官の場合
以下の国賊討伐の勅命が下った。\L玉座に背いた反逆者どもを一網打尽にし、ルドルフ大帝の像の前に引き据えよとの御命令である。\n諸将の奮闘を期待するぞ。

#同盟議長が討伐司令官の場合
諸君らも知っての通り、%s以下の急進派が叛乱を起こした。\L非常処置として、私が指揮を執る。\Lすみやかに民主主義世界の秩序を回復すべく、諸君らの奮戦を期待するものである。

########################################################################
# 　ヤン戦死
########################################################################

#ヤン
……ごめん、ユリアン。ごめん、みんな……。

#ミンツ
ヤン提督……赦してください、赦してください。\nぼくは役ただずだ。\nいちばん肝腎なときに提督のお役に立てなかった……。

#ローエングラム
誰も彼も、敵も味方も、みな予をおいて行ってしまう！\nなぜ予のために生き続けないのか！

#ナレーション
  ヤン・ウェンリーは、多彩な、矛盾と勝利に満たされた短い人生を終えた。比類ない戦争の芸術家でありながら戦争を嫌いぬいていた黒髪の青年は、もう戦わずにすむ場所へ行ってしまったのである。この時点で、ヤン・ウェンリーという恒星の残照を、もっともよく反射することができるのは、彼の被保護者であるユリアン・ミンツしかいなかった……。

########################################################################
#	クーデタ終結処理（軍事裁判）
########################################################################
# 開廷の挨拶（帝国）
……それでは、捕虜を引見するとしよう。

# 開廷の挨拶（同盟）
……それでは、反乱分子どもを連れてきたまえ。

# 被告の呼び出し
%s。\n判決を言い渡す。

# 閉廷宣言（帝国）
以上である。

# 閉廷宣言（同盟）
以上で閉廷とする。

# 閉廷宣言（帝国）
以上で…、!?

# 閉廷宣言（同盟）
以上で閉廷とす…、\n!?

# 暗殺
%s、正義の裁きを受けよ！

# 暗殺のターゲット（男）
ば……ばかなっ。\n…やめろ！

# 暗殺のターゲット（女）
な……っ。\n…おやめなさいっ！

# 暗殺事後報告
ただいま軍医より報告がありました。\n%sは\n出血が著しく意識不明の重体、\nまた%sは服毒しており、\n既にこと切れていた、との事です。

########################################################################
#	亡命処理
########################################################################
# 副官進言（帝国）
……残念ですが、もはや閣下のお力を以てしても、戦局は挽回し難いと思われます。\nここは帝国軍人として\n皇帝陛下の厚恩に報いるべく、もう一方の武力の支援を得て戦いを続けるのが唯一の道であると心得ますが。

# 副官進言（同盟）
……残念ですが、もはや閣下のお力を以てしても、戦局は挽回し難いと思われます。\nここは同盟軍人として\n同盟憲章に殉ずるべく、もう一方の武力の支援を得て戦いを続けるのが唯一の道であると心得ますが。

# 司令官承認（帝国）
武力というのならば、フェザーンではあるまい。\n自由惑星同盟の武力を借りよというのだな。\n話のわかる人物がいれば良いのだが……。

# 司令官承認（同盟）
武力というのならば、フェザーンではあるまい。\n銀河帝国の武力を借りよというのだな。\n話のわかる人物がいれば良いのだが……。

# 司令官拒否（帝国）
差し出がましいぞ、%s。自由惑星同盟を僭称する叛徒どもに頭を下げよというのか。\L裏切り者として生きるより、帝国に殉じた軍人として処刑された方がましだ！

# 司令官拒否（同盟）
差し出がましいぞ、%s。専制主義者どもに頭を下げろというのか。\L裏切り者として生きるより、民主主義に殉じた軍人として処刑された方がましだ！

# 宰相受け入れ（帝国）
…皇帝陛下は卿を客員提督として迎え入れるとの仰せである。\L卿及び卿の部下たちは、以前の功績を考慮して、わが軍のしかるべき階級に任じられるであろう。\L陛下の御慈悲に感謝するのだな。

# 議長受け入れ（同盟）
…自由惑星同盟は貴官を客員提督として迎え入れることを決定した。\L貴官及び貴官の部下たちは、以前の功績を考慮して、わが軍のしかるべき階級に任じられるであろう。

# 司令官受け入れ答え（帝国）
ありがとうございます。この上は、皇帝陛下に忠節を尽くしましょう。

# 司令官受け入れ答え（同盟）
感謝の極みでございます。この恩義は終生忘れませぬ。

# ナレーション（帝国）
自由惑星同盟軍の将官たる%s%sは、銀河帝国に亡命した。以後、同盟軍の内情を知る貴重な存在である彼%sは、客将として遇されることになる。

# ナレーション（同盟）
銀河帝国の将官たる%s%sは、自由惑星同盟に亡命した。以後、帝国軍の内情を知る貴重な存在である彼%sは、客将として遇されることになる。
